export const homeObjOne = {
	primary: true,
	lightBg: false,
	lightTopLine: true,
	lightText: true,
	lightTextDesc: true,
	imgStart: "",
	start: "",
	topLine: "Smart Dashboard Application",
	headline: "About us",
	description: "This is a project for Capstone 1 of Team C1SE.06.",
	// buttonLabel: "About Us",
	urlLinkBtn: "/about",
	img: require("../../assets/img/duytan-logo.png"),
	alt: "duytan-logo",
};

export const mentor1 = {
	primary: false,
	lightBg: true,
	lightTopLine: false,
	lightText: false,
	lightTextDesc: false,
	imgStart: "true",
	start: "true",
	topLine: "Mentor",
	headline: "Ph.D Binh Thanh Nguyen",
	description: "",
	// buttonLabel: "About Us",
	urlLinkBtn: "/about",
	img: require("../../assets/img/male-avatar.svg"),
	alt: "scrum-master",
};

export const mentor2 = {
	primary: true,
	lightBg: false,
	lightTopLine: true,
	lightText: true,
	lightTextDesc: true,
	imgStart: "",
	start: "",
	topLine: "Mentor",
	headline: "M.Sc Huy Truong Dinh",
	description: "",
	// buttonLabel: "About Us",
	urlLinkBtn: "/about",
	img: require("../../assets/img/male-avatar.svg"),
	alt: "mentor",
};

export const hoa = {
	primary: false,
	lightBg: true,
	lightTopLine: false,
	lightText: false,
	lightTextDesc: false,
	imgStart: "true",
	start: "true",
	topLine: "Scrum Master",
	headline: "Hoa Vo Van",
	description: "",
	// buttonLabel: "About Us",
	urlLinkBtn: "/about",
	img: require("../../assets/img/male-avatar.svg"),
	alt: "scrum-master",
};

export const tins = {
	primary: true,
	lightBg: false,
	lightTopLine: true,
	lightText: true,
	lightTextDesc: true,
	imgStart: "",
	start: "",
	topLine: "Team Member",
	headline: "Tin Pham Van",
	description: "",
	// buttonLabel: "About Us",
	urlLinkBtn: "/about",
	img: require("../../assets/img/male-avatar.svg"),
	alt: "team-member-1",
};

export const dong = {
	primary: false,
	lightBg: true,
	lightTopLine: false,
	lightText: false,
	lightTextDesc: false,
	imgStart: "true",
	start: "true",
	topLine: "Team Member",
	headline: "Dong Ky Huu",
	description: "",
	// buttonLabel: "About Us",
	urlLinkBtn: "/about",
	img: require("../../assets/img/male-avatar.svg"),
	alt: "team-member-2",
};

export const kieu = {
	primary: true,
	lightBg: false,
	lightTopLine: true,
	lightText: true,
	lightTextDesc: true,
	imgStart: "",
	start: "",
	topLine: "Team Member",
	headline: "Kieu Tran Thanh",
	description: "",
	// buttonLabel: "About Us",
	urlLinkBtn: "/about",
	img: require("../../assets/img/female-avatar.svg"),
	alt: "team-member-3",
};
